# Python Pre-Commit

default_language_version:
  python: python3.8

default_stages:
  - push
  - commit

exclude: .github/
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # Check Use of Debug Statements
      - id: debug-statements

      # Check File Pattern
      - id: check-json
      - id: check-yaml

      # Deal with Code Style
      - id: double-quote-string-fixer
      - id: trailing-whitespace
      - id: end-of-file-fixer

      # Check File Size
      - id: check-added-large-files


  # PEP 8 Code Linter
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id : flake8
        name: Running Flake 8
        types: [python]

  # Code Quality
  - repo: https://github.com/PyCQA/pylint
    rev: v2.9.5
    hooks:
      - id: pylint
        name: Running PyLint
        types: [python]

  # Import Organizer
  - repo:  https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: Running iSort
        types: [python]

  # Auto formatter
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        name: Running Black
        types: [python]

  # Verify Conventional Commit
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.13
    hooks:
      - id: commitizen
        name: Checking Commit Message
        stages: [commit-msg]

  # - repo: https://github.com/sancheslz/actions_test
  #   rev: main
  #   hooks:
  #   - id: hello
  #     name: Running Hellooooooo
